USE [master]
GO

/****** Object:  Database [AppCRUD]    Script Date: 03.06.2020 11:43:54 ******/
CREATE DATABASE [AppCRUD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AppCRUD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AppCRUD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AppCRUD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AppCRUD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppCRUD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AppCRUD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AppCRUD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AppCRUD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AppCRUD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AppCRUD] SET ARITHABORT OFF 
GO

ALTER DATABASE [AppCRUD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AppCRUD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AppCRUD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AppCRUD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AppCRUD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AppCRUD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AppCRUD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AppCRUD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AppCRUD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AppCRUD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AppCRUD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AppCRUD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AppCRUD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AppCRUD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AppCRUD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AppCRUD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AppCRUD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AppCRUD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AppCRUD] SET  MULTI_USER 
GO

ALTER DATABASE [AppCRUD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AppCRUD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AppCRUD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AppCRUD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AppCRUD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AppCRUD] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AppCRUD] SET  READ_WRITE 
GO

